name: pull-request
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  authenticate-commits:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # We appear to need write permission for both pull-requests and
      # issues in order to post a comment to a pull request.
      pull-requests: write
      issues: write

    steps:
      - name: Checking if the commits can be authenticated
        uses:  sequoia-pgp/authenticate-commits@0f66c8fae548f297b633e10d9091410dde979f1d
